#!/bin/bash
alt="ATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNNTTGGGCGGAGAAGAGAGAATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNNTTGGCGGAGAGGAGAGAATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNTTGGGCGGAGAGGAGAGAATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNNTTGGGCGGAGAGGAGAGATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNNTTGGGCGGAGAGGGAGAATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNNTTGGGGGAGAGGAGAGAATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNNTTGGGCGGAGAGGAGAGAATGCAANNNTTGGGCGGAGAGGAGAGA"
for i in $( eval echo {1..$alt})
do
	if i=="A"|echo"T"

        echo "at base $i "
        echo "T => A"
        echo "**********************"
fi
done

